# Generated by Django 4.2.7 on 2023-11-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='advertiser_management.advertiser'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='img_url',
            field=models.URLField(max_length=300),
        ),
    ]
