# Generated by Django 4.2.7 on 2023-11-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_ad_advertiser_alter_ad_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='landing',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='advertiser_management.advertiser'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='img_url',
            field=models.URLField(max_length=1000),
        ),
    ]
